import { CENTER_HASH_PERCENT } from "./constants";
import {
  applyDefenseFormation,
  applyOffenseFormation,
  getQbDepthForOffenseFormation,
} from "./constants/formations";
import type { GameState, Player } from "./types";

const INITIAL_OFFENSE_FORMATION = "i-form";
const INITIAL_DEFENSE_FORMATION = "4-3";
const INITIAL_QB_UNDER_GUN = true;

const makeOffensePlayers = (): Player[] => [
  {
    id: "O-QB",
    number: 1,
    role: "QB",
    isActive: true,
    isEligible: true,
    routeId: null,
    lanePercent: 50,
    depthFromLos: 3,
  },
  {
    id: "O-RB",
    number: 22,
    role: "RB",
    isActive: true,
    isEligible: true,
    routeId: null,
    lanePercent: 60,
    depthFromLos: 5,
  },
  {
    id: "O-C",
    number: 50,
    role: "C",
    isActive: true,
    isEligible: false,
    routeId: null,
    lanePercent: 50,
    depthFromLos: 1.1,
  },
  {
    id: "O-LG",
    number: 64,
    role: "LG",
    isActive: true,
    isEligible: false,
    routeId: null,
    lanePercent: 44,
    depthFromLos: 1.1,
  },
  {
    id: "O-RG",
    number: 65,
    role: "RG",
    isActive: true,
    isEligible: false,
    routeId: null,
    lanePercent: 56,
    depthFromLos: 1.1,
  },
  {
    id: "O-LT",
    number: 72,
    role: "LT",
    isActive: true,
    isEligible: false,
    routeId: null,
    lanePercent: 38,
    depthFromLos: 1.1,
  },
  {
    id: "O-RT",
    number: 77,
    role: "RT",
    isActive: true,
    isEligible: false,
    routeId: null,
    lanePercent: 62,
    depthFromLos: 1.1,
  },
  {
    id: "O-TE",
    number: 88,
    role: "TE",
    isActive: true,
    isEligible: true,
    routeId: null,
    lanePercent: 70,
    depthFromLos: 1.6,
  },
  {
    id: "O-WR1",
    number: 11,
    role: "WR",
    isActive: true,
    isEligible: true,
    routeId: null,
    lanePercent: 24,
    depthFromLos: 1.8,
  },
  {
    id: "O-WR2",
    number: 19,
    role: "WR",
    isActive: true,
    isEligible: true,
    routeId: null,
    lanePercent: 78,
    depthFromLos: 1.8,
  },
  {
    id: "O-SLOT",
    number: 16,
    role: "SL",
    isActive: true,
    isEligible: true,
    routeId: null,
    lanePercent: 32,
    depthFromLos: 2.5,
  },
];

export const makeDefensePlayers = (): Player[] => [
  {
    id: "D-DT1",
    number: 91,
    role: "DT",
    isActive: true,
    isEligible: false,
    routeId: null,
    lanePercent: 46,
    depthFromLos: -1.1,
  },
  {
    id: "D-DT2",
    number: 98,
    role: "DT",
    isActive: true,
    isEligible: false,
    routeId: null,
    lanePercent: 54,
    depthFromLos: -1.1,
  },
  {
    id: "D-DE1",
    number: 94,
    role: "DE",
    isActive: true,
    isEligible: false,
    routeId: null,
    lanePercent: 38,
    depthFromLos: -1.3,
  },
  {
    id: "D-DE2",
    number: 97,
    role: "DE",
    isActive: true,
    isEligible: false,
    routeId: null,
    lanePercent: 62,
    depthFromLos: -1.3,
  },
  {
    id: "D-LB1",
    number: 52,
    role: "LB",
    isActive: true,
    isEligible: false,
    routeId: null,
    lanePercent: 43,
    depthFromLos: -3.8,
  },
  {
    id: "D-LB2",
    number: 55,
    role: "LB",
    isActive: true,
    isEligible: false,
    routeId: null,
    lanePercent: 50,
    depthFromLos: -4.2,
  },
  {
    id: "D-LB3",
    number: 59,
    role: "LB",
    isActive: true,
    isEligible: false,
    routeId: null,
    lanePercent: 57,
    depthFromLos: -3.8,
  },
  {
    id: "D-LB4",
    number: 58,
    role: "LB",
    isActive: false,
    isEligible: false,
    routeId: null,
    lanePercent: 50,
    depthFromLos: -4.8,
  },
  {
    id: "D-CB1",
    number: 24,
    role: "CB",
    isActive: true,
    isEligible: false,
    routeId: null,
    lanePercent: 24,
    depthFromLos: -2.5,
  },
  {
    id: "D-CB2",
    number: 27,
    role: "CB",
    isActive: true,
    isEligible: false,
    routeId: null,
    lanePercent: 78,
    depthFromLos: -2.5,
  },
  {
    id: "D-S1",
    number: 31,
    role: "S",
    isActive: true,
    isEligible: false,
    routeId: null,
    lanePercent: 35,
    depthFromLos: -7,
  },
  {
    id: "D-S2",
    number: 33,
    role: "S",
    isActive: true,
    isEligible: false,
    routeId: null,
    lanePercent: 65,
    depthFromLos: -7,
  },
];

export const initialGameState: GameState = {
  offense: {
    name: "Offense",
    colorClass: "bg-sky-500/95",
    textClass: "text-sky-100",
    players: applyOffenseFormation(
      makeOffensePlayers(),
      INITIAL_OFFENSE_FORMATION,
    ).map((player) =>
      player.id === "O-QB"
        ? {
            ...player,
            depthFromLos: getQbDepthForOffenseFormation(
              INITIAL_OFFENSE_FORMATION,
              INITIAL_QB_UNDER_GUN,
            ),
          }
        : player,
    ),
  },
  defense: {
    name: "Defense",
    colorClass: "bg-orange-500/95",
    textClass: "text-orange-100",
    players: applyDefenseFormation(
      makeDefensePlayers(),
      INITIAL_DEFENSE_FORMATION,
    ),
  },
  settings: {
    lineOfScrimmageYard: 50,
    ballPlayableYard: 50,
    ballXPercent: CENTER_HASH_PERCENT,
    offenseFormation: INITIAL_OFFENSE_FORMATION,
    defenseFormation: INITIAL_DEFENSE_FORMATION,
    defenseCoverage: "none",
    nearZoneCount: 4,
    qbUnderGun: INITIAL_QB_UNDER_GUN,
    playersLocked: false,
  },
};
